# Mon Oct  9 08:25:50 PM CDT 2023
CC = gcc
CXX = g++
CXXFLAGS = -Wall -std=c++17 -DDEBUG -ggdb
LDFLAGS = -static -lcppunit -L/usr/local/lib/
APPNAME = qpfp
ROOT  = ~/src/qpfp
BLD = $(ROOT)/build
OBJ = $(ROOT)/build
SRC = $(ROOT)/src


# regular expression where % is a wildcard
$(SRC)/%.cpp:
	$(CXX) $(CXXFLAGS) -c -o $@ $^


# regular expression where % is a wildcard
# %.o:%.c
# 	$(CC) $(CFLAGS) -c -o $@ $^

# install 
.PHONY: install
install: man
	cp $(BLD)/$(APPNAME) $(prefix)/bin/$(APPNAME)
	rm $(prefix)/bin/$(APPNAME)

# delete object files & app executable
.PHONY: clean
clean:
	-rm -rf $(BLD)/*